services:
  - type: web
    name: brgybaritan
    env: python
    plan: free
    region: singapore  # Choose the closest region to your users
    buildCommand: |
      pip install --upgrade pip &&
      pip install -r requirements.txt
    startCommand: "gunicorn --worker-tmp-dir /dev/shm --workers=2 --threads=4 --worker-class=gthread app:app"
    envVars:
      - key: PYTHONUNBUFFERED
        value: "true"
      - key: PYTHONPATH
        value: "/opt/render/project/src:/opt/render/project"
      - key: FLASK_ENV
        value: "production"
      - key: FLASK_DEBUG
        value: "0"
      - key: SECRET_KEY
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: SUPABASE_JWT_SECRET
        sync: false
    healthCheckPath: /health-check
    autoDeploy: true
