services:
  - type: web
    name: brgybaritan
    env: python
    region: singapore  # Choose the closest region to your users
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python -m pip install --upgrade pip
    startCommand: gunicorn --worker-tmp-dir /dev/shm --workers=2 --threads=4 --worker-class=gthread app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: PIP_VERSION
        value: 23.0.1
      - key: FLASK_APP
        value: app.py
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: SITE_URL
        sync: false
      - key: EMAIL_HOST
        sync: false
      - key: EMAIL_PORT
        value: "587"
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASSWORD
        sync: false
    healthCheckPath: /health-check
    autoDeploy: true
